version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\vm
image:
- Visual Studio 2017
configuration:
- Release
platform:
- Win32
- x64
skip_tags: true
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%PLATFORM%"=="x64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    cmake --version
    cmake -G %generator% -S . -B build
install:
- git submodule update --init --recursive
build:
  project: c:\projects\vm\build\sqfvm.sln
  verbosity: minimal
  parallel: true
cache:
  - build
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - tests/
test_script:
- cmd: |-
    cd c:\projects\vm
    .\build\Release\sqfvm.exe -a --no-execute-print -i tests\runTests.sqf
